### ISSUE TITLE
Add go forward 10 seconds and go back 10 seconds buttons/double-tap to the player

### ISSUE THREAD

**Issue by codesimo** [Bonfra04/Stronzflix#33] opened 2024-08-21 16:45 UTC
Left arrow and right arrow already work, but adding buttons to go forward and back 10 seconds in the desktop app would make it easy.
![image](https://github.com/user-attachments/assets/7a76f104-bece-4c85-8407-c0f284e3ff4d)

It would also be useful to add double-tap on the left-side and right-side of a touchscreen device (i.e. Android app) to do the same.

**Comment by Bonfra04** [comment] 2024-08-21 17:19
duplicate of #20

**Closed as completed** 2024-08-21 17:19 UTC
Labels: duplicate
