### ISSUE TITLE
Make very long text automatically scroll or wrap

### ISSUE THREAD

**Issue by codesimo** [Bonfra04/Stronzflix#51] opened 2024-08-25 20:21 UTC

**Comment by Bonfra04** [comment] 2024-08-29 21:26
Please be more specific. maybe with some screenshots or specify the part of the application

**Comment by codesimo** [comment] 2024-09-01 16:03
You should have told me earlier, for example when on discord you told me to open this issue :).

I think you were referring to the title of episodes/movies when searching, particularly on anime, which if too long do not allow you to understand either if it is “sub-ita” or the entire title itself.

**Comment by Bonfra04** [comment] 2024-09-01 18:34
Hm, i don't think so. In that case it would be a duplicate of #18

**Closed as not planned** 2024-09-05 09:03 UTC
Labels: duplicate
